// <auto-generated />
namespace EbookWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OverallPropAddedToBookModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverallPropAddedToBookModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201810181759342_OverallPropAddedToBookModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
